dist: xenial
arch: amd64
group: edge
virt: lxd
script:
  - echo "Running Hello world (C program) using IBM advanced tool chain gcc compiler"
  - /opt/at12.0/bin/gcc programs/hello_world.c -o hello_world_c_program
  - ./hello_world_c_program
  - echo "Running Hello world (C++ Program) using IBM advanced tool chain g++ compiler"
  - /opt/at12.0/bin/g++ programs/hello_world.cpp -o hello_world_cpp_program
  - ./hello_world_cpp_program
  - echo "Running Hello world (GO Program) using IBM advanced tool chain gccgo compiler"
  - /opt/at12.0/bin/gccgo hello_world.go -o hello_world_go_program
  - ./hello_world_go_program
  - which node
  - echo "Running Hello world (Nodejs Program)"
  - node programs/hello_world.js
  - rm -rf programs/hello_world_c_program programs/hello_world_cpp_program hello_world_go_program
  - echo "Running Hello world (C program) using default gcc compiler"
  - which gcc
  - gcc programs/hello_world.c -o hello_world_c_program
  - ./hello_world_c_program
  - echo "Running Hello world (C++ Program) using default g++ compiler"
  - which g++
  - g++ programs/hello_world.cpp -o hello_world_cpp_program
  - ./hello_world_cpp_program
  - echo "Running Hello world (GO Program) using default go"
  - go run hello_world.go
  - sudo sh python_interpreter.sh
